### PR TITLE
Breaking runTests in blocks

### PR DESCRIPTION
**Pull request by Iximiel**
This is a followup to #7:

Main changes:
 - I broke up the runTests function in smaller blocks:
   - `runBasicTests` that does the minimum work (positions=yes, timestep=yes, masses=yes and charges=yes)
   - `runForcesTest` (forces=yes)
   - `runVirialTest` (virial=yes)
   - `runEnergyTests` (energy=yes and "energy=yes + virial=yes")
 - removed some code repetition in runEnergyTests
 - compacted how settings are passed between functions via `**` and `dict`s

I think that these changes should make easier to keep the code working

minor changes:
 - I added some types to help vscode in helping me working

The PR is in draft because I have found some bugs(or unwanted behavior?) tha I think can be addressed here:

- (runtest.py:484) In breaking the main function in blocks I discovered that in the monolithic function the `runEnergyTests` block inherits the parameter variable modified by the previous tests in the, so I do not know what should be the wanted settings
- (runtest.py:368,523) we spoke about this this morning: since in check we have `np.divide(np.abs(val1 - val2), val3, out=np.zeros_like(val3), where=val3 > tolerance)` calling check with `val3=tolerance * np.ones(len(md_energy))` cause the division to not be calculated for all of the elements, and so the check passes with 0 as error, making the test pass for all the steps. (I noted it here because the plumed module I am working on for gromacs 24 does not pass the energy in code, but passed the "energy=yes" test with 0% error anyway)

---

A thing that I should have asked in #7, in `getBadge`:
```python
def getBadge(sucess, filen, code, version: str):
    badge = f"[![tested on {version}](https://img.shields.io/badge/{version}-"
    if sucess < 0:
        badge += "failed-red.svg"
    else:
        color = "red"
        if sucess < 5:
            color = "green"
        elif sucess < 20:
            color = "yellow"
        else:
            color = "yellow"
        badge += f"fail%20{sucess}%25-{color}.svg"
```
should the badge for >20% of error be red? because now get things like  and the `elif "%25-red.svg" in inp:` in runtest.py:641 will never be triggered

### CODE REVIEW

**Comment by gtribello** [comment]
Hello

In answer to your questions.

(1) Yes the badge is supposed to be red if the difference is over 20%.  What is there a the moment is a typo.  It is arbitrary though.  We could reserve red for the calculation doesn't even run and have yellow for it runs but the numbers don't match.  Perhaps that makes more sense?  I don't really mind.

(2) The failure to set the params for the energy doesn't really matter.  That test is just checking the energy that is output by the MD code against the energy that is output by PLUMED.  These two sets of quantities should be same regardless of what the input parameters for the MD are.  I've changed it so that the parameters are reset when you run the energy test in the commit I have just pushed.    

(3) I think I have fixed the problems with np.divide in the commit that I have just pushed.

**Comment by Iximiel** [comment]
> (1) Yes the badge is supposed to be red if the difference is over 20%. What is there a the moment is a typo. It is arbitrary though. We could reserve red for the calculation doesn't even run and have yellow for it runs but the numbers don't match. Perhaps that makes more sense? I don't really mind.

If you don't mind I think I'll set put error>20% to red, so that when a 2200% of error is seen will apper as a failure and not as a humble warning
It might make more sense divide the "runs, but it is sligtly wrong" from "runs but it is completely wrong", because the latter is even worse that "it cannot even start", since it actually does something.

> (3) I think I have fixed the problems with np.divide in the commit that I have just pushed.

I am not 100% sure, you check equality between floating points, that usually is not a good idea.
In the cases of  `tolerance * np.ones(len(md_energy))`, knowing that condition on the`where`, we could simply pass the tolerance of check to be 0.0, since we are sure that the denominator is always different from zero. I should have thinked about this last week...
like:
```python
.writeReportAndTable(
        "energy",
        "MD code potential energy passed correctly",
        md_energy,
        pl_energy,
        tolerance * np.ones(len(md_energy)),
        tolerance=0.0
    )
```

and I should change the "tolerance" keyword for check  and writeReportAndTable in  "denominatorTolerance"

**Comment by gtribello** [comment]
That all sounds fine to me.  If you make those changes and put them here I will approve the PR.

**Comment by gtribello** [comment]
Does this latest commit mean that you are ready to merge this or not @Iximiel?  Thanks

**Comment by Iximiel** [comment]
Yes, sorry for the delay

**Pull request merged**
